services:  
  backend:
    build: ./backend
    container_name: grr_docker_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://umegaeshan:umega123URA@ac-x5spvm2-shard-00-00.maiykpr.mongodb.net:27017,ac-x5spvm2-shard-00-01.maiykpr.mongodb.net:27017,ac-x5spvm2-shard-00-02.maiykpr.mongodb.net:27017/?ssl=true&replicaSet=atlas-fhjgu9-shard-0&authSource=admin&appName=Cluster0
    
  frontend:
    build: ./frontend
    container_name: grr_docker_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules